# Generated by Django 3.1.5 on 2021-05-20 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='created',
            new_name='created_on',
        ),
    ]
