# Generated by Django 3.1.5 on 2021-05-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20210520_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='created_on',
            new_name='created',
        ),
    ]
