# Generated by Django 3.1.5 on 2021-06-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20210520_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='description',
        ),
        migrations.AddField(
            model_name='hotel',
            name='long_description',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='short_description',
            field=models.TextField(default=1, max_length=165),
            preserve_default=False,
        ),
    ]
